image:
- Visual Studio 2015
environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
  matrix:

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    # - PYTHON: "C:\\Python27"
    # - PYTHON: "C:\\Python33"
    # - PYTHON: "C:\\Python34"
    # - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
      BIN_NAME: appr-%APPVEYOR_REPO_TAG_NAME%-win-x64
      PYTHON_ARCH: "64"
      PYTHON_VERSION: "2.7.x"
    # - PYTHON: "C:\\Python33-x64"
    # - PYTHON: "C:\\Python34-x64"
    # - PYTHON: "C:\\Python35-x64"

install:
  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install setuptools>=6.0"
  - "python --version"
  - "git clone https://github.com/google/jsonnet.git"
  - "cd jsonnet"
  - "python setup.py build --compiler=mingw64"
  # # Upgrade to the latest version of pip to avoid it displaying warnings
  # # about it being out of date.
  # - "pip install --disable-pip-version-check --user --upgrade pip"

  # # We need wheel installed to build wheels
  # # - "pip install -r requirements_dev.txt"
  # - "pip install jsonnet"
  # - "pip install -e ."
  # - "pip install -e git+https://github.com/pyinstaller/pyinstaller.git#egg=pyins
#  taller"
build: off


test_script: []
  # Run the project tests
  #- "py.test --cov=appr --cov-report=html --cov-report=term-missing  --verbose tests"

after_test:
  # If tests are successful, create binary packages for the project.
  - "pyinstaller --add-data appr/jsonnet;appr/jsonnet --onefile bin/appr"
  - ps: "ls dist"
  - "copy dist\\appr.exe %BIN_NAME%.exe"
  - "mkdir registry"
  - "copy dist\\appr.exe registry\\appr.exe"
  - "7z a registry-%BIN_NAME%-helm-plugin.zip registry\\*.*"
  - ps: "ls dist"
  - ps: "ls registry"
  - "C:\\projects\\appr\\registry\\appr.exe version quay.io"

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: "%BIN_NAME%.exe"
  - path: registry-%BIN_NAME%-helm-plugin.zip
    type: zip
