matrix:
  include:
    - os: linux
      sudo: false
      language: python
      env:
        - MAKECMD=lint
        - BIN_NAME=appr-$TRAVIS_OS_NAME-x64
    - os: linux
      sudo: false
      language: python
      env:
        - MAKECMD=test
        - BIN_NAME=appr-$TRAVIS_OS_NAME-x64
    - os: osx
      language: generic
      env:
        - MAKECMD=test
        - BIN_NAME=appr-$TRAVIS_OS_NAME-x64

install:
  - if [ "$MAKECMD" == "test" ] ; then pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip ; fi
  - if [ "$MAKECMD" == "test" ] && [ "$TRAVIS_OS_NAME" == "linux" ] ; then pip install -U coveralls ; fi
  - pip install -r requirements_dev.txt
  - pip install -e .

script:
  - PYTHONPATH="." make $MAKECMD

after_success:
  - echo $BIN_NAME
  - if [ "$MAKECMD" == "test" ] ; then pyinstaller --add-data "appr/jsonnet/:appr/jsonnet" --onefile bin/appr ; fi
  - if [ "$MAKECMD" == "test" ] ; then mkdir -p appr-helm/registry; fi
  - if [ "$MAKECMD" == "test" ] ; then mv dist/appr $BIN_NAME; fi
  - if [ "$MAKECMD" == "test" ] ; then chmod +x $BIN_NAME; fi
  - if [ "$MAKECMD" == "test" ] ; then cp $BIN_NAME appr-helm/registry/appr; fi
  - if [ "$MAKECMD" == "test" ] && [ "$TRAVIS_OS_NAME" == "linux" ] ; then coveralls ; fi


deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  overwrite: true
  file:
    - $BIN_NAME
    - bin/apprc
  skip_cleanup: true
  on:
    tags: true
    condition: $MAKECMD = "test"
